# fly.toml app configuration file generated for bible-mem on 2024-10-04T12:42:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bible-mem'
primary_region = 'iad'

[mounts]
  source = "pb_data"
  destination = "/pb_data"

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
